### ISSUE TITLE
Plugin Ideas and Translation Issues

### ISSUE THREAD

**Issue by Mwexim** [AlexLew95/GameAPI#2]
New ideas:
`create new area named %string% for minigame %string% with lowbound %location% and highbound %location%` Creates a new area
`delete area %string% from minigame %string%`
`reset area %string% from minigame %string%` Resets the area back to it's original state (the state where the area was when it was created)
And then some event stuff like `on area create` and also some expressions for area's

Translation Issues 
Please make it so that you also can write `minigame` in stead of `mini game` or `mini-game`
`minis-games` is not a word. Maybe in French, but not in English. `mini-games` is correct, `minis-games` not.

**Comment by Olyno** [comment]
Of course, that's a good idea I think. I will work on it for futures versions

**Comment by Olyno** [comment]
New version of GameAPI. Please remake an issue with new syntaxes to be easier for me to implement your idea.
