### ISSUE TITLE
JavaDoc Page Dead on README.md

### ISSUE THREAD

**Issue by ilsubyeega** [AlexLew95/GameAPI#7]
Not releated in game

**My problem is:
The page below is dead
https://alexlew95.github.io/GameAPI/javadoc/

I'm using ``GameAPI`` as: 
 - [x] Java developper
 - [x] Skript developper
 - [ ] Yaml developper

developper -> developer

My Skript version (``/ver skript`` in the console) is:
 - [x] The latest
 - [ ] Other (please precise it: ``here``)

My minecraft version (``/ver`` in the console) is:
 - [x] > or = 1.9.4
 - [ ] < 1.9.4

**

**My code is:**

none

**Comment by ilsubyeega** [comment]
and just founded alexlew95 was the old name and olyno is the new one so I just figured out
https://olyno.github.io/GameAPI/javadoc/

**Comment by Olyno** [comment]
Indeed my name is not "alexlew95" but "olyno" now, so all link must to be changed. Thanks for this report !
